# -*- coding: utf-8 -*-
"""test_program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jO4p1fS81MLd3LBEQ4xwKlfT2bX2MPW
"""

import unittest
from question import Question

class TestQuestionMarkResponse(unittest.TestCase):
    def test_mark_response_single_correct(self):
        question = Question('single')
        question.set_correct_answer('A')
        marks = question.mark_response('A')
        self.assertEqual(marks, 1.0)

    def test_mark_response_single_incorrect(self):
        question = Question('single')
        question.set_correct_answer('B')
        marks = question.mark_response('A')
        self.assertEqual(marks, 0.0)

    def test_mark_response_multiple_all_correct(self):
        question = Question('multiple')
        question.set_correct_answer('A, B, C')
        marks = question.mark_response('A, B, C')
        self.assertEqual(marks, 1.0)

    def test_mark_response_multiple_partial_correct(self):
        question = Question('multiple')
        question.set_correct_answer('A, B, C')
        marks = question.mark_response('A, C')
        self.assertAlmostEqual(marks, 0.67, 2)

    def test_mark_response_multiple_incorrect(self):
        question = Question('multiple')
        question.set_correct_answer('A, B, C')
        marks = question.mark_response('D')
        self.assertEqual(marks, 0.0)

    def test_mark_response_type_short(self):
        question = Question('short')
        marks = question.mark_response('Any response')
        self.assertEqual(marks, 0.0)

if __name__ == '__main__':
    unittest.main()